SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM
    BOOK_SALES s
    JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
    JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE TO_CHAR(s.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY 
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY
    AUTHOR_ID, CATEGORY DESC